server:
  port: 10026
spring:
  profiles:
    active: peer2

eureka:
  instance:
    hostname: peer2
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
  client:
    register-with-eureka: true
#    fetch-registry: true
    service-url:
      defaultZone: http://eureka:123456@${eureka.instance.hostname}:10025/eureka/,http://eureka:123456@${eureka.instance.hostname}:10027/eureka/

