server:
  port: 10027
spring:
  profiles:
    active: peer3

eureka:
  instance:
    hostname: peer3
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
  client:
    register-with-eureka: true
#    fetch-registry: true
    service-url:
      C