server:
  port: 10025
spring:
  profiles:
    active: peer1

eureka:
  instance:
    hostname: peer1
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
  client:
    register-with-eureka: true
#    fetch-registry: true
    service-url:
      defaultZone: http://eureka:123456@${eureka.instance.hostname}:10026/eureka/,http://eureka:123456@${eureka.instance.hostname}:10027/eureka/
