server:
  port: 8899

spring:
  application:
    name: consul-service
  profiles:
    active: dev
  cloud:
    consul:
      discovery:
        enabled: true
        register: true
        deregister: true
        prefer-ip-address: true
        health-check-interval: 30s
        health-check-critical-timeout: 30s
        health-check-path: /actuator/info
        instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}


#      discovery:
#        enabled: true
#        register: true
#        heartbeat:
#          enabled: true
#          ttl-unit: s
#          ttl-value: 30
#        prefer-ip-address: true


#logging:
#  config: classpath:logback-develop.xml


#description: I am boy
#student:
#  name: nihao
#  age: 30
#  sex: man
