
server:
  port: 9600
spring:
  application:
    name: dynamic-route-service
  profiles:
    active: dev
  thymeleaf:
    cache: false
    mode: HTML
  redis:
    host: 127.0.0.1
    port: 6379
    password:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password:  123456
    url: jdbc:mysql://localhost:3306/dynamic-route?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowMultiQueries=true
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      max-lifetime: 1800000
      idle-timeout: 30000
      auto-commit: true
      pool-name: PbHikariCP
      connection-test-query: SELECT 1
      connection-timeout: 30000

mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.zhliang.springcloud.dynamic.route.entity


eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
  client:
    service-url:
      defaultZone: http://eureka:123456@localhost:10025/eureka/

