server:
  port: 9000
spring:
  application:
    name: consumer-service

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://eureka:123456@localhost:10025/eureka/

